name: hive-dnstap-integrator

on:
  push:
    tags:
      - "hive-dnstap-integrator-[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build and push hive-dnstap-integrator
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: gbenson/hive-dnstap-integrator
          tags: |
            type=match,pattern=hive-dnstap-integrator-(\d+\.\d+\.\d+),group=1

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          file: services/dns/tap/integrator/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/hive-dnstap-integrator-') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
